export const PREFIX = {
  BANNER: 'JPSBNR',
  PARTNER: 'JPSPTR',
  TEAM: 'JPSTM',
  ARTICLE: 'JPSARC',
  DOCUMENTATION: 'JPSDOC',
  VOLUNTEER: 'JPSVTR',
  CAREER: 'JPSCRR',
  EVENT: 'JPSEVT',
  ADMIN: 'JPSADM',
};
